### ISSUE TITLE
Add Dockerfile to make this easier to run

### ISSUE THREAD

**Issue by bertybuttface** [jakecoppinger/matrix-chatgpt-bot#1]
Will also help allow it to be included in [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy)

I could knock something up but I don't know if you have any strong preferences?

**Comment by jakecoppinger** [comment]
Happy for you to put one in, I won't be able to get to it this weekend unfortunately! No strong preferences, though I don't think it's mature enough to be in [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) 😄
