### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by eravion** [jakecoppinger/matrix-chatgpt-bot#2]
Sorry, maybe a stupid question ...

I did that: 
https://github.com/jakecoppinger/matrix-chatgpt-bot#setting-up-the-account

And I have this error: 
yarn run v1.22.19
$ rm -f tsconfig.tsbuildinfo && npx tsc
src/index.ts:32:34 - error TS2345: Argument of type '{ sessionToken: string; }' is not assignable to parameter of type '{ sessionToken: string; clearanceToken: string; markdown?: boolean; apiBaseUrl?: string; backendApiBaseUrl?: string; userAgent?: string; accessTokenTTL?: number; accessToken?: string; headers?: Record<string, string>; }'.
  Property 'clearanceToken' is missing in type '{ sessionToken: string; }' but required in type '{ sessionToken: string; clearanceToken: string; markdown?: boolean; apiBaseUrl?: string; backendApiBaseUrl?: string; userAgent?: string; accessTokenTTL?: number; accessToken?: string; headers?: Record<string, string>; }'.

32   const chatGPT = new ChatGPTAPI({
                                    ~
33     sessionToken: chatGPTApiKey
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
34   })
   ~~~

  node_modules/chatgpt/build/index.d.ts:308:9
    308         clearanceToken: string;
                ~~~~~~~~~~~~~~
    'clearanceToken' is declared here.


Found 1 error in src/index.ts:32

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Howto check where the probleme come from please ?

**Comment by Dual-0** [comment]
clearanceToken is missing here. It was added in [chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api) commit [c083ad64d9b111bce917b3adfd42715ae7f2d319](https://github.com/transitive-bullshit/chatgpt-api/commit/c083ad64d9b111bce917b3adfd42715ae7f2d319)

**Comment by jakecoppinger** [comment]
Ah that makes sense. I won't have time to fix this in the coming days unfortunately. PRs very welcome :)

**Comment by bertybuttface** [comment]
Completely untested for now but I've started working on this as I can't sleep:

https://github.com/jakecoppinger/matrix-chatgpt-bot/pull/4

**Comment by bertybuttface** [comment]
Closing as fixed.
