### ISSUE TITLE
Add support for follow ups

### ISSUE THREAD

**Issue by bertybuttface** [jakecoppinger/matrix-chatgpt-bot#5]
Right now we create a new conversation every time we reply to ChatGPT. The API wrapper we are using supports follow ups though, from the docs:

"If you want to track the conversation, use the conversationId and messageId in the result object, and pass them to sendMessage as conversationId and parentMessageId respectively."

```
// send a message and wait for the response
let res = await api.sendMessage('What is OpenAI?')
console.log(res.response)

// send a follow-up
res = await api.sendMessage('Can you expand on that?', {
  conversationId: res.conversationId,
  parentMessageId: res.messageId
})
```

We should find some way of tying the conversationId and parentMessageId to the matrix room or even do something clever with the new threaded replies support in Matrix / Element.

**Comment by bertybuttface** [comment]
I have some code to do this now for new style threads. Will put in a PR once encrypted chats fixes are merged and the new ChatGPT API support is merged.

**Comment by jakecoppinger** [comment]
Using threads sounds great. On holiday at the moment so I don't have time to add this unfortunately.

Last time I checked the matrix bot sdk doesn't have a thread reply function - I've used this in the past and it's worked great.

```
/**
 * Send a thread reply.
 * @param client Matrix client
 * @param param1 Object containing text, root_event_id and roomId. root_event_id is the event_id
 * of the message the thread "replying" to.
 */
 export async function sendThreadReply(client: MatrixClient, { text, root_event_id, roomId }: { text: string, root_event_id: string, roomId: string }): Promise<void> {
  const content = {
    body: text,
    msgtype: "m.text",
    "org.matrix.msc1767.text": text,
    "m.relates_to": {
      event_id: root_event_id,
      is_falling_back: true,
      "m.in_reply_to": {
        "event_id": root_event_id
      },
      rel_type: "m.thread"
    }
  }
  await client.sendEvent(roomId, "m.room.message", content);
}
```

**Comment by bertybuttface** [comment]
This is fixed by: https://github.com/jakecoppinger/matrix-chatgpt-bot/pull/18
