### ISSUE TITLE
Enable Discussions for GitHub Repo

### ISSUE THREAD

**Issue by bertybuttface** [jakecoppinger/matrix-chatgpt-bot#9]
This will help keep issues clear of user support requests.

**Comment by bertybuttface** [comment]
Might be better handled by a Matrix chat room, not sure.

**Comment by jakecoppinger** [comment]
I'd rather a Matrix room - I'll make one now and add it to the README (and add it here)

**Comment by jakecoppinger** [comment]
Created https://matrix.to/#/#matrix-chatgpt-bot:matrix.org

**Comment by jakecoppinger** [comment]
Added to the readme, thanks for raising this :)
